### ISSUE TITLE
Release to environment fails

### ISSUE THREAD

**Issue by joricteixeira** [chef-partners/vsts-chef#11]
I've been trying to use 'Release cookbook to environment, but I always get the error:

Cannot find module 'fs-extra'

I've tried in the Linux agent and Hosted VS2017 agent, and the error remains the same

Output:

##[debug]Evaluating condition for step: 'Release cookbook version to environment'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> (Boolean) True
##[debug]Expanded: True
##[debug]Result: True
##[section]Starting: Release cookbook version to environment
==============================================================================
Task         : Release cookbook version to environment (Chef)
Description  : Releases a cookbook by releasing the cookbook constraint on the specified Chef environment
Version      : 1.3.9
Author       : Chef
Help         : [More information](https://github.com/chef-partners/vsts-chef/wiki/release-cookbook-version-to-environment)
==============================================================================
##[debug]agent.workFolder=d:\a
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_REDACTED
##[debug]loading ENDPOINT_AUTH_PARAMETER_REDACTED_PASSWORD
##[debug]loading ENDPOINT_AUTH_PARAMETER_REDACTED_USERNAME
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_REDACTED
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CHEFCOOKBOOKNAME
##[debug]loading INPUT_CHEFCOOKBOOKVERSION
##[debug]loading INPUT_CHEFENVNAME
##[debug]loading INPUT_CHEFSERVERENDPOINT
##[debug]loaded 11
##[debug]task result: Failed
##[error]Unhandled: Cannot find module 'fs-extra'
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Cannot find module 'fs-extra'
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Cannot find module 'fs-extra'
##[section]Finishing: Release cookbook version to environment

**Comment by stuartpreston** [comment]
Hi @joricteixeira - thanks for reporting this, we're investigating this currently and will get to back to you asap.

**Comment by stuartpreston** [comment]
Hi @joricteixeira - we've just pushed out a set of updates to the tasks, this should actually the requirement for that module completely.  Please refresh and try and adding the task again.

**Comment by joricteixeira** [comment]
Hi @stuartpreston it worked! Thanks!
