### ISSUE TITLE
Release Cookbook Version: Server response of 400 should fail the task with debug info

### ISSUE THREAD

**Issue by stuartpreston** [chef-partners/vsts-chef#15]
# Version
1.4.21

# Repro steps:
Use the task, setting the cookbook version number to a non-SemVer (x.y.z) number, e.g. `1340971` and execute it.

# Result:
Task completes successfully but does not apply the cookbook version contraint to the environment (as verified by `knife environment show <environment>`

# Expected Result:
Task fails and reports an error in the log such as 
```
ERROR: Chef::Exceptions::ValidationFailed: Option cookbook_versions's value {"mycookbook"=>"1340971"} should be a valid set of cookbook version requirements!
```

This is probably a more generic note about trapping the HTTP 400 errors that come back through the API code.

**Comment by russellseymour** [comment]
Fixed in version 1.5.4 - https://github.com/chef-partners/vsts-chef/wiki/1.5.4

Any response from the Chef Server that is not an HTTP 200 will result in that task failing and the reason for the failure displayed in the log.
