### ISSUE TITLE
Test Kitchen task not using correct command

### ISSUE THREAD

**Issue by russellseymour** [chef-partners/vsts-chef#17]
The Test Kitchen task is running

`chef exec kitchen verify`

but it should be running

`chef exec kitchen test`

**Comment by stuartpreston** [comment]
Doesn’t `kitchen test` run destroy first before all the steps, as well as a destroy at the end? Verify stops short of the final destroy and needs an additional destroy if used.

**Comment by russellseymour** [comment]
Looking at this more and seeing how it should be used.
Will look at creating a task that has a drop down of actions that relate to the Test Kitchen commands.

**Comment by russellseymour** [comment]
Fixed in version [1.6.1](https://github.com/chef-partners/vsts-chef/wiki/1.6.1)

Please refer to the [Test Kitchen](https://github.com/chef-partners/vsts-chef/wiki/test-kitchen) page for the changes that have been made to the task.
