### ISSUE TITLE
Multiple releases running on the same release server conflict over the private key file

### ISSUE THREAD

**Issue by aullom1** [chef-partners/vsts-chef#20]
# Setup

Configure two release definitions using the Execute Knife (Chef) task.  Configure the task to create and delete the private key.

Use the same deployment queue for both releases.  The deployment queue should have at least two agents so that the releases can run in parallel.

Queue both releases, one at a time, but in quick succession.

# Expected Result

The Execute Knife (Chef) task should not report any errors for either release.

# Actual Result

One release succeeds while the other fails with the error `Your private key could not be loaded from c:/windows/temp/********.pem`.

There is an additional warning that states `Failed to read the private key c:/windows/temp/********.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - c:/windows/temp/********.pem>`.

This happens because both releases are using the same .pem file.  The first release to finish will delete the file before the other release has finished with the file.

# Desired Fix

Name the .pem file with the `Release.ReleaseId` and `Release.EnvironmentId` to guarantee that releases (and environments) running in parallel will not conflict over the .pem file.

**Comment by russellseymour** [comment]
@aullom1 Good spot.

I will make the change to the code and run some tests and hopefully do a release next week.

**Comment by russellseymour** [comment]
@aullom1 

I have looked into this. I agree that the filename of the pem file should be changed to avoid this conflict. However the way that the filename is determined affects all tasks that use it. In addition all tasks can be used in the either the Build or Release phases.

So to avoid the conflict you have raised and the possibility of tasks being used in either phase, I am going to set the filename of the private key to the `Agent.Id`.

As each agent can only run one job at a time, this should be enough to make the files different enough to handle your scenario.

**Comment by aullom1** [comment]
@russellseymour Good point about the Build process.  I hadn't considered that one.

**Comment by russellseymour** [comment]
@aullom1 Finally released this. Apologies for the delay.

The version that contains this fix is 1.6.13

Will close this now, but please reopen if you have issues with this fix.
