### ISSUE TITLE
Change location of chef-client.bat in Execute Chef Client task

### ISSUE THREAD

**Issue by darodecap** [chef-partners/vsts-chef#6]
I am attempting to use the Execute Chef Client task in our VSTS release process.  When it runs,  it appears to be successful, but has actually failed to run chef-client because it is expecting chef-client.bat to be in C:\opscode\bin.

![image](https://user-images.githubusercontent.com/10271764/33027716-8452f4e4-cdd9-11e7-927b-aa496229045f.png)

When I bootstrap a windows node using the following command:

`knife bootstrap windows winrm hostame.my.domain -x domain\user --node-name my.friendly.name`

it installs the windows client into c:\opscode\chef.

Can we fix this task to use c:\opscode\chef\bin\chef-client.bat, instead of c:\opscode\bin\chef-client.bat?  Or is there a way to change the install location of the chef-client when I bootstrap a node?

Thanks!

**Comment by russellseymour** [comment]
Hello @darodecap 

I will fix the task and publish a new version.

Thanks for highlighting this issue.

**Comment by darodecap** [comment]
@russellseymour Fantastic!  Thanks!

**Comment by russellseymour** [comment]
@darodecap 

I have released a new version of the extension, 1.1.6, which has the correct path in it.

I will close this issue, however if you have more problems please feel free to reopen it.

**Comment by darodecap** [comment]
@russellseymour  I've confirmed that this works.  Thanks again for the quick turnaround.
