### ISSUE TITLE
Artifactory supermarket support

### ISSUE THREAD

**Issue by Happycoil** [chef-partners/vsts-chef#7]
The extension should have a task to upload to an artifactory supermarket instance using basic authentication.

**Comment by russellseymour** [comment]
Hello,

Would the be possible to use the JFrog Artifactory extension in the VSTS Marketplace - https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-artifactory - to accomplish this.

If it does not do what you require could you add some specifics on what you require?

Thanks. Sorry about the delay in replying to you about this.

**Comment by Happycoil** [comment]
That might work, I'll take a look. At first glance it looks like you'll have to package the cookbook on your own.

Anyway, all I really need is a task which wraps [knife-art](https://github.com/JFrogDev/knife-art). Maybe I should just make one for myself... Are the vsts-chef task definitions available somewhere?

**Comment by russellseymour** [comment]
That makes sense. I will setup and test a task that uses `knife-art` to upload a cookbook.

At the moment the VSTS Chef Extension code is not available publicly as it is in VSTS so we can take advantage of the pipelines there. I am looking at mirroring the code to here so people can see it - trouble with that is how to handle PRs.

**Comment by russellseymour** [comment]
We have just released a new version (1.3.9) of the extension that has two new tasks:

- [Install Gem](https://github.com/chef-partners/vsts-chef/wiki/install-gem)
- [Execute Knife](https://github.com/chef-partners/vsts-chef/wiki/execute-knife)

The first will allow you to install `knife-art` and the second task will allow you to run the Artifcatory knife commands. 

Hope this helps you with what you need to do.

**Comment by russellseymour** [comment]
Closing issue as there is now a mechanism to run knife commands using the 'Execute Knife' Task
