### ISSUE TITLE
Add task to allow running knife command

### ISSUE THREAD

**Issue by EmFl** [chef-partners/vsts-chef#8]
Hello,
I was wondering if it was possible to have a task that would allow us to run knife command. The idea is to use VSTS to manage the chef-repo in git and push changes. I think today it is limited to the cookbook management.

Thanks

**Comment by russellseymour** [comment]
Hello,

We have just released an updated version of the extension to the marketplace, version 1.2.62. This has two new tasks, one of which is to "Install ChefDK".

If you used this task (or have already setup ChefDK in a the agent) and then the "Command Line" task to call `knife`, would this suffice?

If not please could you say what it is that you require that would make this better for you. I assume that one of the things maybe to be able to reuse endpoint infromation.

**Comment by EmFl** [comment]
Hello,
Thanks for the update, I think having a knife step or a bash step with chef context would still be beneficial. At this time and thanks to your new version, I was able to do what I want by :
1. Adding the chefdk step
2. adding the cookbook upload step referencing a wrong path and checking do not delete key + continue on error (this fails but all I want is the key...)
3. Adding a bash step that contain this : 
```
cat <<EOT >> /tmp/knife.rb
chef_server_url          "https://mychefurl.com/organizations/myorg"
node_name 'mynodename'
client_key '/tmp/vsts-task.pem'
EOT

knife node list --config  /tmp/knife.rb 
```
Maybe instead of a new task, modifying the chefdk step to provide an option to preconfigure knife would be enough.

**Comment by russellseymour** [comment]
I am pleased that you have a found a work around, but it would be better if this was a bit cleaner.

I will look at adding a `knife` task that is linked with the credentials that have been set in VSTS. This will mean that it can be modified if required and it is possible to remove things from the agent.
The reason that I am keen on enabling this is that I do not want credentials left over on a hosted agent for example.

The end result will be what you are doing now, but you will not have a failed step in your pipeline.

**Comment by russellseymour** [comment]
We have just released a new version (1.3.9) of the extension that has two new tasks:

- [Install Gem](https://github.com/chef-partners/vsts-chef/wiki/install-gem)
- [Execute Knife](https://github.com/chef-partners/vsts-chef/wiki/execute-knife)

These should assist you in running `knife` commands without having to have a failing task.

**Comment by EmFl** [comment]
Hello,
I'm sorry I haven't been able to test this before. Thanks for the update !
I tried today to do a knife node list but getting the following error message : 
```
******************************************************************************
Starting: Execute Knife
******************************************************************************
==============================================================================
Task         : Execute Knife (Chef)
Description  : Execute Knife command with specified options
Version      : 1.3.9
Author       : Chef
Help         : [More information](https://github.com/chef-partners/vsts-chef/wiki/execute-knife)
==============================================================================
bc17ca81-a8d0-44a1-bdfe-57718ff8249e exists true
(node:202) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'private_key' of undefined
******************************************************************************
Finishing: Execute Knife
******************************************************************************
```

**Comment by russellseymour** [comment]
@EmFl We have released some updates this week that should take care of issues for the Knife Exec task.

Could you try it again please? (My apologies for the delay in getting back to you)

**Comment by stuartpreston** [comment]
Closing this due to age.  @EmFl if you experience further issues please check the Wiki page and raise an issue.  Thanks.
